import { table } from "console";
import { MigrationInterface, QueryRunner, Table } from "typeorm";

export class CreateAccountTable1645226527437 implements MigrationInterface {

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS accounts (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
        email text not null,
        hashed_password text not null,
        full_name text not null,
        
        primary key(id)
      )`);

    await queryRunner.query(`
      ALTER TABLE accounts ADD CONSTRAINT accounts_unique_email UNIQUE(email)
    `);

    await queryRunner.query(`CREATE INDEX idx_accounts_uuid ON accounts(uuid)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS accounts
    `);
  }

}
